allowCompoundWords: true
dictionaries:
  - en_US
  - en-gb
  - eo
  - fonts
  - html
  - git
  - lorem-ipsum
  - markdown
  - misc
  - softwareTerms
enableGlobDot: true
features:
  weighted-suggestions: true
globRoot: ${cwd}
ignorePaths:
  - .*ignore
  - .git
  - .github/CODE_OF_CONDUCT.*
  - .vscode/extensions.json
  - cspell.config.yml
language: en,eo,ja
useGitignore: true
version: '0.2'
words:
  - aegisub
  - alac
  - imgbotconfig
  - kito
  - kuron
  - kuroné
  - nullrise
